User History Continued
mouimet-infinisoft/steve pull request #9
Opened 2022-07-14 18:55 UTC by Jaal-tech

- Filter to fetch all selectedId history
- switch component to get icon based on action that user did.

2022-07-14 19:27 UTC, mouimet-infinisoft commented on src/features/contacts/libs/details/history.js
> +  switch (true) {
```js
const iconPresets = {
create: <FastfoodIcon />,
update: <UploadIcon />,
anything: <AnyIcon />
}
```

Dont you think its would be more scalable ?

2022-07-15 05:37 UTC, mouimet-infinisoft commented
Fix conflicts asap :)

2022-07-15 16:30 UTC, Jaal-tech commented on src/features/contacts/libs/details/history.js
> +  switch (true) {
Fixed

2022-07-15 20:02 UTC, mouimet-infinisoft requested changes

2022-07-15 20:02 UTC, mouimet-infinisoft commented on src/features/contacts/libs/details/card.tabs.js
> -    component: <NotImplemented />,
Rollback that change

2022-07-16 03:31 UTC, mouimet-infinisoft requested changes

2022-07-16 03:31 UTC, mouimet-infinisoft commented on src/components/header-subtitle/index.js
> +        <Typography variarnt="body1" color="text.primary" textTransform={"capitalize"}>
There is a typo
`variarnt="body1"`

2022-07-16 03:31 UTC, mouimet-infinisoft commented on src/components/header-subtitle/index.js
> +        <Typography variarnt="body2" color="text.secondary" component={"span"}>
There is a typo
`variarnt="body1"`

2022-07-16 03:31 UTC, mouimet-infinisoft commented on src/components/header-subtitle/index.js
> +        <Typography variarnt="body2" color="text.secondary" component={"span"}>
There is a typo
`variarnt="body1"`

2022-07-16 03:31 UTC, mouimet-infinisoft commented on src/components/scroll-container/index.js
> +import { Avatar, Divider, Grid, IconButton } from "@mui/material"
Please start to use default import instead of named imports for these reasons:
1. Named imports cannot be lazy load
2. Named import loads the intire package, so bundle is huge

```typescript
import Avatar from "@mui/material/Avatar"
import Divider from "@mui/material/Divider"
import Grid from "@mui/material/Grid"
import IconButton from "@mui/material/IconButton"```

2022-07-16 03:31 UTC, mouimet-infinisoft commented on src/features/contacts/libs/details/history.detail.js
> +                <HeaderAndSubtitle label={label} tag={tag} value={value} display="flex" gap={theme.spacing(1)} />
3 problems: 
1. Risk of runtime error if list is undefined
Replace by
`  {list?.map(({ label, tag, value }) =>`
2. Destructure is useless
` 
{list?.map((props) =>
            (
HeaderAndSubtitle {...props} display="flex" gap={theme.spacing(1)} />`
3. In React each time you are looping a key props is required on the first container element
Use generateId() helpers to generate a unique key
The key controls the rendering lifecycle. Therefore, its up to you to choose the right key based on requirement.
` 
{list?.map((props) =>
            (
HeaderAndSubtitle key={generateId()} {...props} display="flex" gap={theme.spacing(1)} />`

2022-07-16 03:31 UTC, mouimet-infinisoft commented on src/features/contacts/libs/details/history.detail.js
> +                <>
Need a key here.

2022-07-18 15:53 UTC, Jaal-tech commented on src/features/contacts/libs/details/card.tabs.js
> -    component: <NotImplemented />,
Fixed

2022-07-18 15:53 UTC, Jaal-tech commented on src/components/header-subtitle/index.js
> +        <Typography variarnt="body1" color="text.primary" textTransform={"capitalize"}>
Fixed

2022-07-18 15:53 UTC, Jaal-tech commented on src/components/header-subtitle/index.js
> +        <Typography variarnt="body2" color="text.secondary" component={"span"}>
Fixed

2022-07-18 15:53 UTC, Jaal-tech commented on src/components/header-subtitle/index.js
> +        <Typography variarnt="body2" color="text.secondary" component={"span"}>
Fixed

2022-07-18 15:53 UTC, Jaal-tech commented on src/features/contacts/libs/details/history.detail.js
> +                <HeaderAndSubtitle label={label} tag={tag} value={value} display="flex" gap={theme.spacing(1)} />
yeah I agree, forgot to add keys.

2022-07-18 15:53 UTC, Jaal-tech commented on src/features/contacts/libs/details/history.detail.js
> +                <>
Fixed

2022-07-18 23:38 UTC, mouimet-infinisoft approved these changes
Good job

2022-07-18 23:38 UTC, merged